# Travis CI is used to test platforms that github-actions currently doesn't support
# without either self-hosting or some finnicky work-around. Also, some tests
# are troublesome to migrate since GH Actions runs tests not in a tty.
language: c

git:
  depth: 1

branches:
  only:
  - dev
  - release
  - master
  - travisTest

matrix:
  include:
    - name: My custom job
      os: linux
      dist: xenial
      arch: amd64
      script:
        - echo hello
